#!/usr/bin/env python3
"""
Set up CSV files for tests and benchmarks.

Usage:
    python3 scripts/provision_data.py                     # every suite
    python3 scripts/provision_data.py duckdb rust-csv     # named suites only
    python3 scripts/provision_data.py --check             # report gaps, download nothing
    python3 scripts/provision_data.py --force             # re-download even if present
    python3 scripts/provision_data.py tpch --sf 10        # TPC-H lineitem at sf10 too
    python3 scripts/provision_data.py kaggle              # opt-in; needs credentials
    python3 scripts/provision_data.py kaggle --tier mid

Needs the `duckdb` (for tpch) and `toml` modules: pip install -r scripts/requirements.txt
"""

from __future__ import annotations

import argparse
import base64
import concurrent.futures
import io
import json
import os
import shutil
import sys
import tarfile
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from dataclasses import dataclass

import layout
from layout import ROOT, data_dir, suite_dir

PARALLEL = 16


@dataclass(frozen=True)
class Suite:
    repo: str          # "owner/name" on GitHub
    commit: str        # immutable pin; a branch name would defeat the point
    transport: str     # "tarball" or "files" — see the note on SUITES
    ref: str = ""      # human-readable label for `commit`, if it has one


SUITES: dict[str, Suite] = {
    "duckdb": Suite(
        repo="duckdb/duckdb",
        ref="v1.3.2",
        commit="0b83e5d2f68bc02dfefde74b846bd039f078affa",
        transport="tarball",
    ),
    "postgres": Suite(
        repo="postgres/postgres",
        commit="9a08585e8e59068d0ede7d47cd037915a42e1362",
        transport="files",
    ),
    "rust-csv": Suite(
        repo="BurntSushi/rust-csv",
        commit="05612e87e6e92910d40d7214b70952b8434fef9b",
        transport="tarball",
    ),
}


#: Everything a bare `provision_data.py` runs.
DEFAULT_SUITES = [*SUITES, "tpch"]

#: Every suite this script knows how to provision.
ALL_SUITES = [*DEFAULT_SUITES, "kaggle"]


#: Scale factors generated with no `--sf`. sf1: ~0.77 GB, sf10: ~7.9 GB, sf100: ~79 GB
TPCH_DEFAULT_SFS = (1,)

#: Bytes of lineitem CSV per scale factor, for the disk-space guard below.
TPCH_BYTES_PER_SF = 790_000_000


def tpch_dir() -> str:
    return data_dir("tpch")


def duckdb_connect():
    """An in-memory DuckDB with the tpch extension loaded.
    """
    try:
        import duckdb
    except ImportError:
        raise Failure(
            "the tpch suite is generated by DuckDB, but the `duckdb` module is "
            "not installed: pip install -r scripts/requirements.txt"
        ) from None
    con = duckdb.connect()
    con.execute("SET enable_progress_bar = false;")
    con.execute("INSTALL tpch; LOAD tpch;")
    return con


def tpch_generate(sf: int, dest: str) -> None:
    """Generate `lineitem` at `sf` into `dest`, one dbgen child at a time."""
    parts_dir = os.path.join(os.path.dirname(dest), ".parts")
    os.makedirs(parts_dir, exist_ok=True)

    children = sf if sf > 1 else 0
    steps = children or 1
    tmp = dest + ".part"

    try:
        with open(tmp, "wb") as out:
            for step in range(steps):
                part = os.path.join(parts_dir, f"lineitem-{step}.csv")
                con = duckdb_connect()
                try:
                    if children:
                        con.execute("CALL dbgen(sf=?, children=?, step=?);",
                                    [sf, children, step])
                    else:
                        con.execute("CALL dbgen(sf=?);", [sf])
                    # HEADER only on the first part.
                    header = "true" if step == 0 else "false"
                    # `|` is dbgen's own separator
                    con.execute(
                        f"COPY lineitem TO ? "
                        f"(FORMAT csv, DELIMITER '|', HEADER {header});",
                        [part],
                    )
                finally:
                    con.close()
                with open(part, "rb") as f:
                    shutil.copyfileobj(f, out, length=1 << 22)
                os.remove(part)
                print(f"  sf{sf}: part {step + 1}/{steps} "
                      f"({out.tell() / 1e9:.1f} GB)", flush=True)
        os.replace(tmp, dest)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
        shutil.rmtree(parts_dir, ignore_errors=True)


def run_tpch(sfs: tuple[int, ...], check: bool, force: bool) -> list[str]:
    os.makedirs(tpch_dir(), exist_ok=True)
    print(f"tpch: generated by DuckDB dbgen at sf{', sf'.join(map(str, sfs))} "
          f"-> {layout.describe('tpch')}/")

    wanted = [(sf, os.path.join(tpch_dir(), f"lineitem-sf{sf}.csv")) for sf in sfs]

    if check:
        for sf, dest in wanted:
            size = os.path.getsize(dest) if os.path.exists(dest) else 0
            state = f"{size / 1e9:.2f} GB" if size else "absent"
            print(f"  lineitem-sf{sf}.csv: {state}")
        on_disk = {f for f in os.listdir(tpch_dir()) if f.endswith(".csv")}
        return report_gaps_generated('tpch', on_disk)

    todo = [(sf, d) for sf, d in wanted if force or not os.path.exists(d)]
    for sf, dest in wanted:
        if (sf, dest) not in todo:
            print(f"  lineitem-sf{sf}.csv already present; "
                  f"use --force to regenerate")

    need = sum(sf for sf, _ in todo) * TPCH_BYTES_PER_SF
    free = shutil.disk_usage(tpch_dir()).free
    if need > free:
        raise Failure(
            f"tpch: sf{'+sf'.join(str(sf) for sf, _ in todo)} needs about "
            f"{need / 1e9:.0f} GB but only {free / 1e9:.0f} GB is free"
        )

    for sf, dest in todo:
        tpch_generate(sf, dest)

    on_disk = {f for f in os.listdir(tpch_dir()) if f.endswith(".csv")}
    return report_gaps_generated('tpch', on_disk)


def report_gaps_generated(name: str, on_disk: set[str]) -> list[str]:
    """Like `report_gaps`, but a missing file is only a note."""
    expected = manifest_names(name)
    missing = sorted(expected - on_disk)
    extra = sorted(on_disk - expected)
    if extra:
        print(f"  note: {len(extra)} generated file(s) are not in manifest.toml "
              f"and will not be benchmarked (e.g. {extra[0]})")
    if missing:
        print(f"  note: {len(missing)} manifest entr(ies) not generated; "
              f"the bench skips them ({', '.join(missing)})")
    return []


KAGGLE_TIERS: dict[str, int | None] = {
    "small": 10_000_000,
    "mid": 1_000_000_000,
    "full": None,
}

#: A bare `provision_data.py` should not decide to download 974 GB.
KAGGLE_DEFAULT_TIER = "small"

#: Kaggle rate-limits, and these are whole files, so stay below `PARALLEL`.
KAGGLE_PARALLEL = 4

#: Attempts per file before giving up, with exponential backoff between them.
KAGGLE_RETRIES = 5

#: Files larger than this report progress while they download.
KAGGLE_PROGRESS_BYTES = 1_000_000_000

#: Single-file download endpoint.
KAGGLE_API = "https://www.kaggle.com/api/v1/datasets/download"


def kaggle_sources() -> dict[str, dict]:
    """The committed download list: key -> {dataset, path, size}."""
    path = os.path.join(suite_dir("kaggle"), "sources.toml")
    if not os.path.exists(path):
        raise Failure(
            f"{path} is missing. It is committed, so restore it with:\n"
            f"    git checkout -- {os.path.relpath(path, ROOT)}"
        )
    with open(path, "rb") as f:
        return tomllib.load(f).get("files", {})


def kaggle_token_paths() -> list[str]:
    """Where a `kaggle.json` may live, in the order the official CLI looks."""
    if os.environ.get("KAGGLE_CONFIG_DIR"):
        return [os.path.join(os.environ["KAGGLE_CONFIG_DIR"], "kaggle.json")]
    xdg = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    return [
        os.path.join(xdg, "kaggle", "kaggle.json"),
        os.path.expanduser("~/.kaggle/kaggle.json"),
    ]


def kaggle_auth() -> tuple[str, str]:
    """Kaggle credentials, from the environment or a `kaggle.json`."""
    user = os.environ.get("KAGGLE_USERNAME", "").strip()
    key = os.environ.get("KAGGLE_KEY", "").strip()
    if user and key:
        return user, key

    paths = kaggle_token_paths()
    for path in paths:
        if not os.path.exists(path):
            continue
        try:
            with open(path, "rb") as f:
                cfg = json.load(f)
            return cfg["username"], cfg["key"]
        except (KeyError, json.JSONDecodeError) as e:
            raise Failure(f"{path} is not a valid Kaggle token ({e})") from None

    looked = ", ".join(paths)
    raise Failure(
        "kaggle needs credentials: put an API token at "
        f"{paths[0]} (Kaggle -> Settings -> API -> Create New Token), or set "
        f"KAGGLE_USERNAME and KAGGLE_KEY. Looked in: {looked}"
    )


class _StripAuthOnRedirect(urllib.request.HTTPRedirectHandler):
    """Drop the Authorization header when a redirect leaves the Kaggle host."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        new = super().redirect_request(req, fp, code, msg, headers, newurl)
        if new is None:
            return None
        if urllib.parse.urlsplit(newurl).netloc != urllib.parse.urlsplit(req.full_url).netloc:
            new.headers = {k: v for k, v in new.headers.items()
                           if k.lower() != "authorization"}
        return new


def kaggle_opener() -> urllib.request.OpenerDirector:
    return urllib.request.build_opener(_StripAuthOnRedirect)


def kaggle_stream(url: str, auth: tuple[str, str], dest_tmp: str,
                  label: str, expected: int) -> int:
    """Stream `url` to `dest_tmp`, returning the byte count written."""
    token = base64.b64encode(f"{auth[0]}:{auth[1]}".encode()).decode()
    req = urllib.request.Request(url, headers={
        "User-Agent": "csveee-fetch-data",
        "Authorization": f"Basic {token}",
    })

    opener = kaggle_opener()
    with opener.open(req, timeout=300) as r:
        declared = r.headers.get("Content-Length")
        declared = int(declared) if declared and declared.isdigit() else None
        written = 0
        next_report = KAGGLE_PROGRESS_BYTES
        with open(dest_tmp, "wb") as out:
            while chunk := r.read(1 << 20):
                out.write(chunk)
                written += len(chunk)
                if expected >= KAGGLE_PROGRESS_BYTES and written >= next_report:
                    pct = f" ({100 * written / expected:.0f}%)" if expected else ""
                    print(f"    {label}: {written / 1e9:.1f} GB{pct}", flush=True)
                    next_report += KAGGLE_PROGRESS_BYTES

    if declared is not None and written != declared:
        # No label: the caller prefixes the key.
        raise Failure(f"truncated transfer, {written} of {declared} bytes")
    return written


def kaggle_unzip(tmp: str, path: str) -> None:
    """Replace `tmp` with its contents if Kaggle wrapped the file in a zip."""
    with open(tmp, "rb") as f:
        if f.read(4) != b"PK\x03\x04":
            return

    want = os.path.basename(path)
    with zipfile.ZipFile(tmp) as z:
        members = [m for m in z.infolist() if not m.is_dir()]
        if not members:
            raise Failure(f"{path}: downloaded zip is empty")
        member = next((m for m in members
                       if os.path.basename(m.filename) == want), None)
        if member is None:
            if len(members) > 1:
                raise Failure(
                    f"{path}: zip holds {len(members)} files and none is "
                    f"named {want!r}"
                )
            member = members[0]
        unzipped = tmp + ".unz"
        with z.open(member) as src, open(unzipped, "wb") as out:
            shutil.copyfileobj(src, out, length=1 << 22)
    os.replace(unzipped, tmp)


def kaggle_reason(e: Exception) -> str:
    if isinstance(e, urllib.error.HTTPError):
        return f"HTTP {e.code}"
    if isinstance(e, urllib.error.URLError):
        return str(e.reason)
    return str(e)


def kaggle_retry_after(e: Exception, delay: float) -> float | None:
    """Seconds to wait before retrying `e`, or None if retrying is pointless."""
    if isinstance(e, urllib.error.HTTPError):
        if e.code not in (429, 500, 502, 503, 504):
            return None
        after = e.headers.get("Retry-After")
        if after and after.strip().isdigit():
            return float(after)
        return delay
    return delay


def kaggle_fetch_one(key: str, src: dict, root: str,
                     auth: tuple[str, str]) -> tuple[str, int]:
    """Download one file into the corpus. Returns (key, bytes written)."""
    dest = os.path.join(root, key)
    tmp = dest + ".part"

    # `safe=""` matters: nested files 404 if their slashes reach the endpoint
    # unencoded (the extra path segments stop matching the route).
    url = (
        f"{KAGGLE_API}/{urllib.parse.quote(src['dataset'])}"
        f"/{urllib.parse.quote(src['path'], safe='')}"
    )

    delay = 2.0
    for attempt in range(KAGGLE_RETRIES):
        try:
            kaggle_stream(url, auth, tmp, key, src["size"])
            break
        except (Failure, urllib.error.URLError) as e:
            if os.path.exists(tmp):
                os.remove(tmp)

            wait = kaggle_retry_after(e, delay)
            if wait is None or attempt == KAGGLE_RETRIES - 1:
                code = getattr(e, "code", None)
                kind = Gone if code in (403, 404) else Failure
                raise kind(f"{key}: {kaggle_reason(e)}") from None
            print(f"    {key}: {kaggle_reason(e)}, retrying in {wait:.0f}s",
                  flush=True)
            time.sleep(wait)
            delay *= 2

    kaggle_unzip(tmp, src["path"])
    size = os.path.getsize(tmp)
    os.replace(tmp, dest)
    return key, size


def kaggle_tier_keys(sources: dict[str, dict], tier: str) -> list[str]:
    cap = KAGGLE_TIERS[tier]
    return sorted(k for k, v in sources.items() if cap is None or v["size"] <= cap)


def run_kaggle(tier: str, check: bool, force: bool) -> list[str]:
    sources = kaggle_sources()
    root = data_dir("kaggle")
    wanted = kaggle_tier_keys(sources, tier)
    wanted_bytes = sum(sources[k]["size"] for k in wanted)

    print(f"kaggle: {len(sources)} sampled files, tier {tier} selects "
          f"{len(wanted)} ({wanted_bytes / 1e9:.2f} GB) "
          f"-> {layout.describe('kaggle')}/")

    os.makedirs(root, exist_ok=True)
    on_disk = {f for f in os.listdir(root) if f.endswith(".csv")}

    if check:
        have = [k for k in wanted if k in on_disk]
        print(f"  {len(on_disk)} CSV file(s) on disk, "
              f"{len(have)}/{len(wanted)} of this tier")
        return report_gaps_kaggle(sources, wanted, on_disk)

    todo = [k for k in wanted if force or k not in on_disk]
    if not todo:
        print(f"  all {len(wanted)} present; use --force to re-download")
        return report_gaps_kaggle(sources, wanted, on_disk)

    need = sum(sources[k]["size"] for k in todo)
    free = shutil.disk_usage(root).free
    if need > free:
        raise Failure(
            f"kaggle: tier {tier} needs about {need / 1e9:.0f} GB more but only "
            f"{free / 1e9:.0f} GB is free at {root}. Point CSVEEE_DATA_KAGGLE "
            f"(or data.local.toml) somewhere bigger, or use a smaller --tier."
        )

    auth = kaggle_auth()
    print(f"  downloading {len(todo)} file(s), {need / 1e9:.2f} GB")

    done = 0
    changed: list[str] = []
    failures: list[str] = []
    gone: list[str] = []

    def one(key: str) -> tuple[str, int] | None:
        try:
            return kaggle_fetch_one(key, sources[key], root, auth)
        except Gone as e:
            gone.append(str(e))
            return None
        except Failure as e:
            failures.append(str(e))
            print(f"  FAILED: {e}", file=sys.stderr)
            return None

    with concurrent.futures.ThreadPoolExecutor(KAGGLE_PARALLEL) as pool:
        for result in pool.map(one, todo):
            done += 1
            if result is None:
                continue
            key, size = result
            if size != sources[key]["size"]:
                changed.append(key)
            if done % 25 == 0 or done == len(todo):
                print(f"  {done}/{len(todo)} files", flush=True)

    problems = []
    if failures:
        problems.append(f"kaggle: {len(failures)} file(s) failed to download")
    if gone:
        print(f"  note: {len(gone)} file(s) are no longer served (private, "
              f"withdrawn, or renamed upstream); the manifest simply will not "
              f"cover them. First: {gone[0]}")
        if len(gone) > max(10, len(wanted) // 4):
            problems.append(
                f"kaggle: {len(gone)} of {len(wanted)} file(s) in this tier "
                f"returned 403/404 — too many to be attrition; check that the "
                f"credential is valid"
            )
    if changed:
        print(f"  note: {len(changed)} file(s) differ in size from sources.toml "
              f"(upstream changed; e.g. {changed[0]})")

    on_disk = {f for f in os.listdir(root) if f.endswith(".csv")}
    return problems + report_gaps_kaggle(sources, wanted, on_disk)


def report_gaps_kaggle(sources: dict[str, dict], wanted: list[str],
                       on_disk: set[str]) -> list[str]:
    """Gap report for a tiered suite."""
    expected = manifest_names("kaggle")
    if not expected:
        print("  note: no manifest.toml yet — after downloading, run "
              ".venv/bin/python scripts/sniff_dialects.py kaggle")
        return []

    in_tier = set(wanted)
    missing = sorted((expected & in_tier) - on_disk)
    deselected = sorted(expected - in_tier - on_disk)
    extra = sorted(on_disk - expected)

    if extra:
        print(f"  note: {len(extra)} file(s) on disk are not in manifest.toml "
              f"and will not be tested (e.g. {extra[0]})")
    if deselected:
        print(f"  note: {len(deselected)} manifest entr(ies) are outside this "
              f"tier; the harness skips them")
    if missing:
        print(f"  MISSING: {len(missing)} file(s) this tier expects are not "
              f"present (e.g. {missing[0]})")
        return [f"kaggle: {len(missing)} manifest entries missing in tier"]
    return []



class Failure(Exception):
    pass


class Gone(Failure):
    """A file upstream no longer serves: private, withdrawn, or renamed."""


def local_name(upstream_path: str) -> str:
    """Upstream path -> flat local filename (`a/b/c.csv` -> `a_b_c.csv`)."""
    return upstream_path.replace("/", "_")


def _request(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "csveee-fetch-data"})
    token = os.environ.get("GITHUB_TOKEN")
    if token and "api.github.com" in url:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return r.read()
    except urllib.error.HTTPError as e:
        raise Failure(f"HTTP {e.code} for {url}") from None
    except urllib.error.URLError as e:
        raise Failure(f"{e.reason} for {url}") from None


def write_atomic(dest: str, body: bytes) -> None:
    """Write via a temp file: an interrupted run leaves no half-written CSV."""
    tmp = dest + ".part"
    with open(tmp, "wb") as f:
        f.write(body)
    os.replace(tmp, dest)


def fetch_via_tarball(suite: Suite, out_dir: str) -> dict[str, bytes]:
    """Stream the source tarball and pull every *.csv out of it."""
    url = f"https://codeload.github.com/{suite.repo}/tar.gz/{suite.commit}"
    blob = _request(url)

    found: dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tar:
        for member in tar:
            if not member.isfile() or not member.name.endswith(".csv"):
                continue
            parts = member.name.split("/", 1)
            if len(parts) != 2:
                continue
            handle = tar.extractfile(member)
            if handle is None:
                continue
            found[parts[1]] = handle.read()
    return found


def fetch_via_files(suite: Suite, out_dir: str) -> dict[str, bytes]:
    """List the tree via the API, then pull each CSV individually."""
    tree_url = (
        f"https://api.github.com/repos/{suite.repo}/git/trees/"
        f"{suite.commit}?recursive=1"
    )
    tree = json.loads(_request(tree_url))
    if tree.get("truncated"):
        raise Failure(
            f"{suite.repo}: the git tree listing was truncated, so the CSV set "
            f"would be incomplete. Switch this suite to transport='tarball'."
        )

    paths = [
        e["path"] for e in tree.get("tree", [])
        if e.get("type") == "blob" and e["path"].endswith(".csv")
    ]

    def one(path: str) -> tuple[str, bytes]:
        raw = (
            f"https://raw.githubusercontent.com/{suite.repo}/"
            f"{suite.commit}/{urllib.parse.quote(path)}"
        )
        return path, _request(raw)

    found: dict[str, bytes] = {}
    with concurrent.futures.ThreadPoolExecutor(PARALLEL) as pool:
        for path, body in pool.map(one, paths):
            found[path] = body
    return found


def manifest_names(name: str) -> set[str]:
    """Files the test harness expects: manifest.toml + overrides.toml."""
    names: set[str] = set()
    for fname in ("manifest.toml", "overrides.toml"):
        path = os.path.join(suite_dir(name), fname)
        if not os.path.exists(path):
            continue
        with open(path, "rb") as f:
            names |= set(tomllib.load(f).get("files", {}))
    return names


def report_gaps(name: str, on_disk: set[str]) -> list[str]:
    """Compare what the harness expects against what is present.
    """
    expected = manifest_names(name)
    if not expected:
        return []

    missing = sorted(expected - on_disk)
    extra = sorted(on_disk - expected)

    if extra:
        print(f"  note: {len(extra)} file(s) upstream are not in manifest.toml "
              f"and will not be tested (e.g. {extra[0]})")
    if missing:
        suite = SUITES[name]
        pin = suite.ref or suite.commit[:10]
        print(f"  MISSING: {len(missing)} file(s) the manifest expects are not "
              f"present (e.g. {missing[0]})")
        return [f"{name}: {len(missing)} manifest entries missing at pin {pin}"]
    return []


def run_suite(name: str, check: bool, force: bool) -> list[str]:
    suite = SUITES[name]
    out_dir = data_dir(name)
    os.makedirs(out_dir, exist_ok=True)

    pin = suite.ref or suite.commit[:10]
    print(f"{name}: {suite.repo} @ {pin} ({suite.transport}) "
          f"-> {layout.describe(name)}/")

    if check:
        on_disk = {f for f in os.listdir(out_dir) if f.endswith(".csv")}
        print(f"  {len(on_disk)} CSV file(s) on disk")
        return report_gaps(name, on_disk)

    existing = {f for f in os.listdir(out_dir) if f.endswith(".csv")}
    if existing and not force:
        print(f"  {len(existing)} already present; use --force to re-download")
        return report_gaps(name, existing)

    fetcher = fetch_via_tarball if suite.transport == "tarball" else fetch_via_files
    found = fetcher(suite, out_dir)
    if not found:
        raise Failure(f"{name}: no CSV files found at {pin}")

    seen: dict[str, str] = {}
    for path in found:
        n = local_name(path)
        if n in seen:
            raise Failure(f"{name}: {path!r} and {seen[n]!r} both flatten to {n!r}")
        seen[n] = path

    for path, body in found.items():
        write_atomic(os.path.join(out_dir, local_name(path)), body)

    total = sum(len(b) for b in found.values())
    print(f"  {len(found)} downloaded ({total / 1e6:.1f} MB)")
    return report_gaps(name, set(seen))


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    p.add_argument("suites", nargs="*", choices=[*ALL_SUITES, []], default=[],
                   help="suite names (default: every suite except kaggle, "
                        "which is opt-in)")
    p.add_argument("--check", action="store_true",
                   help="report what is present or missing; download nothing")
    p.add_argument("--force", action="store_true",
                   help="re-download even when the suite is already populated")
    p.add_argument("--tier", default=KAGGLE_DEFAULT_TIER,
                   choices=list(KAGGLE_TIERS),
                   help="how much of the kaggle sample to fetch "
                        f"(default: {KAGGLE_DEFAULT_TIER}); "
                        "small is 0.72 GB, mid 73 GB, full 974 GB")
    p.add_argument("--sf", default=None,
                   help="tpch scale factors to generate, comma-separated "
                        f"(default: {','.join(map(str, TPCH_DEFAULT_SFS))}); "
                        "sf10 is 7.9 GB and sf100 is 79 GB")
    args = p.parse_args()

    if args.sf is not None and args.suites and "tpch" not in args.suites:
        p.error("--sf only applies to the tpch suite, which these suites exclude")
    if args.tier != KAGGLE_DEFAULT_TIER and "kaggle" not in args.suites:
        p.error("--tier only applies to the kaggle suite; name it explicitly")
    try:
        sfs = tuple(int(x) for x in args.sf.split(",")) if args.sf else TPCH_DEFAULT_SFS
    except ValueError:
        p.error(f"--sf wants comma-separated integers, got {args.sf!r}")
    if any(sf < 1 for sf in sfs):
        p.error("--sf wants positive integers")

    names = args.suites or (ALL_SUITES if args.check else DEFAULT_SUITES)

    problems: list[str] = []
    for name in names:
        try:
            if name == "tpch":
                problems += run_tpch(sfs, args.check, args.force)
                continue
            if name == "kaggle":
                problems += run_kaggle(args.tier, args.check, args.force)
                continue
            problems += run_suite(name, args.check, args.force)
        except Failure as e:
            problems.append(str(e))
            print(f"  FAILED: {e}", file=sys.stderr)

    if problems:
        sys.stdout.flush()
        print(f"\n{len(problems)} problem(s):", file=sys.stderr)
        for x in problems:
            print(f"  - {x}", file=sys.stderr)
        return 1

    if "kaggle" not in names:
        print("\nnote: kaggle is opt-in (credentials, and 0.72 GB at its "
              "smallest): python3 scripts/provision_data.py kaggle")
    print("\nOK. `cargo test` now covers the full corpus.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
