#!/usr/bin/env python3
"""
Sniff CSV dialects using DuckDB and generate manifest.toml files.

Usage:
    .venv/bin/python scripts/sniff_dialects.py duckdb postgres rust-csv kaggle

Needs the `duckdb` and `toml` modules: pip install -r scripts/requirements.txt

Run scripts/provision_data.py first.
"""

import sys
import os
import duckdb
import toml

import layout

HAND_MAINTAINED = {"fixtures", "tpch"}


def sniff_file(con: duckdb.DuckDBPyConnection, path: str) -> dict | None:
    """Run DuckDB's sniff_csv on a single file and return dialect dict."""
    try:
        row = con.execute(
            "SELECT Delimiter, Quote, Escape, NewLineDelimiter, Comment, HasHeader, Columns "
            # sample_size=-1: sniff the whole file, we care for correctness and have time
            "FROM sniff_csv(?, sample_size=-1)",
            [path],
        ).fetchone()
    except Exception as e:
        print(f"  WARN: sniff failed for {path}: {e}", file=sys.stderr)
        error_msg = str(e).lower()
        if "not utf-8 encoded" in error_msg or "invalid unicode" in error_msg:
            return {"encoding": "non-utf-8"}
        return {}

    delimiter, quote, escape, newline, comment, has_header, columns = row

    dialect = {}

    # Only non-default values, to keep the manifest compact. Defaults:
    # delimiter=",", quote='"', escape='"', terminator="CRLF", has_headers=true
    if delimiter != ",":
        dialect["delimiter"] = delimiter
    if quote == "(empty)":
        dialect["quote"] = ""
    elif quote != '"':
        dialect["quote"] = quote
    if escape == "(empty)":
        dialect["escape"] = ""
    elif escape != '"':
        dialect["escape"] = escape
    if newline == "\\r\\n":
        dialect["terminator"] = "CRLF"
    elif newline == "\\r":
        dialect["terminator"] = "CR"
    elif newline == "\\n":
        dialect["terminator"] = "LF"
    if comment != "(empty)":
        dialect["comment"] = comment
    if not has_header:
        dialect["has_headers"] = False

    dialect["columns"] = len(columns)

    return dialect


def sniff_directory(directory: str) -> dict:
    """Sniff all CSV files in a directory and return a manifest dict."""
    con = duckdb.connect()

    # Flat directories and kaggle-style subdirectories alike.
    csv_files = []
    for root, _dirs, files in os.walk(directory):
        for f in files:
            if f.endswith(".csv"):
                csv_files.append(os.path.join(root, f))
    csv_files.sort()

    files = {}
    for path in csv_files:
        rel_path = os.path.relpath(path, directory)
        print(f"  sniffing {rel_path}...", end="", flush=True)
        dialect = sniff_file(con, path)
        if dialect is not None:
            files[rel_path] = dialect
            print(" ok")
        else:
            print(" FAILED")

    con.close()
    return {"files": files}


def write_manifest(name: str, manifest: dict):
    """Write manifest.toml into the suite's committed metadata directory."""
    path = os.path.join(layout.suite_dir(name), "manifest.toml")
    header = (
        f"# Auto-generated by scripts/sniff_dialects.py using DuckDB "
        f"{duckdb.__version__}'s CSV sniffer.\n"
        "# Do NOT edit manually — put overrides in overrides.toml instead.\n"
        "#\n"
        "# Dialect values are only present when they differ from defaults:\n"
        "#   delimiter = \",\"  quote = '\"'  escape = '\"'  terminator = \"CRLF\"  has_headers = true\n"
        "#\n"
        "# Empty string for quote/escape means quoting is disabled.\n\n"
    )
    with open(path, "w") as f:
        f.write(header)
        toml.dump(manifest, f)
    print(f"  wrote {path} ({len(manifest['files'])} files)")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <suite> [<suite> ...]", file=sys.stderr)
        sys.exit(1)

    for name in sys.argv[1:]:
        if name in HAND_MAINTAINED:
            print(
                f"ERROR: {name} is hand-maintained — its manifest.toml records "
                "deliberate, reviewed dialects and is not sniffer output. Refusing "
                "to overwrite it.",
                file=sys.stderr,
            )
            continue
        if not os.path.isdir(layout.suite_dir(name)):
            print(f"ERROR: no suites/{name} directory", file=sys.stderr)
            continue
        directory = layout.data_dir(name)
        if not os.path.isdir(directory):
            print(f"ERROR: {name}: no CSVs at {directory} — "
                  f"run scripts/provision_data.py", file=sys.stderr)
            continue
        print(f"Processing {name} ({layout.describe(name)}/)...")
        manifest = sniff_directory(directory)
        write_manifest(name, manifest)


if __name__ == "__main__":
    main()